import type { Food } from './model.ts';
// Shared with Chinese search so the name on a result can also be searched.
export const breadNames: [string, string][] = [
  ['white with whole wheat swirl', '全麦花纹白面包'],
  ['marble rye and pumpernickel', '双色黑麦面包'],
  ['whole grain white', '全谷物白面包'],
  ['wheat or cracked wheat', '小麦或碎麦面包'],
  ['wheat, sprouted', '发芽小麦面包'],
  ['sprouted wheat', '发芽小麦面包'],
  ['whole-wheat', '全麦面包'],
  ['whole wheat', '全麦面包'],
  ['white wheat', '白小麦面包'],
  ['whole grain', '全谷物面包'],
  ['multi-grain', '杂粮面包'],
  ['multigrain', '杂粮面包'],
  ['cracked-wheat', '碎麦面包'],
  ['french or vienna', '法式或维也纳面包'],
  ['cornmeal and molasses', '玉米粉糖蜜面包'],
  ['chapati or roti', '印度薄饼'],
  ['chappatti or roti', '印度薄饼'],
  ['pita with fruit', '水果皮塔饼'],
  ['pound cake type', '磅蛋糕式面包'],
  ['salvadoran sweet cheese', '萨尔瓦多甜奶酪面包'],
  ['sweet potato', '红薯面包'],
  ['sunflower meal', '葵花籽粉面包'],
  ['spanish coffee', '西班牙式咖啡面包'],
  ['boston brown', '波士顿棕面包'],
  ['irish soda', '爱尔兰苏打面包'],
  ['high protein', '高蛋白面包'],
  ['sour dough', '酸面团面包'],
  ['sourdough', '酸面团面包'],
  ['pan dulce', '甜面包'],
  ['protein', '蛋白强化面包'],
  ['pumpernickel', '粗黑麦面包'],
  ['rye', '黑麦面包'],
  ['wheat', '小麦面包'],
  ['oat bran', '燕麦麸面包'],
  ['oatmeal', '燕麦面包'],
  ['rice bran', '米糠面包'],
  ['barley', '大麦面包'],
  ['rice', '米面包'],
  ['soy', '大豆面包'],
  ['white', '白面包'],
  ['black', '黑面包'],
  ['cornbread', '玉米面包'],
  ['blue corn', '蓝玉米面包'],
  ['pita', '皮塔饼'],
  ['naan', '印度烤饼'],
  ['puri', '印度油炸薄饼'],
  ['paratha', '印度层酥薄饼'],
  ['italian', '意式面包'],
  ['cuban', '古巴式面包'],
  ['egg', '鸡蛋面包'],
  ['potato', '土豆面包'],
  ['cheese', '奶酪面包'],
  ['onion', '洋葱面包'],
  ['cinnamon', '肉桂面包'],
  ['raisin', '葡萄干面包'],
  ['banana', '香蕉面包'],
  ['pumpkin', '南瓜面包'],
  ['zucchini', '西葫芦面包'],
  ['vegetable', '蔬菜面包'],
  ['fruit', '水果面包'],
  ['nut', '坚果面包'],
  ['gluten-free', '无麸质面包'],
  ['gluten free', '无麸质面包'],
  ['crumbs', '面包屑'],
  ['sticks', '面包棒'],
  ['stuffing', '面包填料'],
  ['dough', '面团'],
  ['roll', '小餐包'],
];
// Editorial translations of USDA descriptions; unmatched terms remain visible.
export const foodTranslationPhrases: [string, string][] = [
  ...breadNames.map(([en, zh]): [string, string] => [`bread, ${en}`, zh]),
  ['spoonbread', '玉米布丁式面包'],
  ['breadsticks', '面包棒'],
  ['crackers, crispbread, rye', '黑麦脆面包'],
  [
    'crackers, melba toast, rye (includes pumpernickel)',
    '黑麦薄烤面包片（含粗黑麦面包）',
  ],
  ['crackers, rye', '黑麦饼干'],
  ['sandwich-type with cheese filling', '奶酪夹心型'],
  ['muffin, english, rye', '黑麦英式松饼'],
  ['rolls, dinner, rye', '黑麦餐包'],
  ['roll, rye', '黑麦餐包'],
  ['rye flour, dark', '深色黑麦粉'],
  ['rye flour, medium', '中色黑麦粉'],
  ['rye flour, light', '浅色黑麦粉'],
  ['rye flour', '黑麦粉'],
  ['rye grain', '黑麦粒'],
  ['brown rice', '糙米'],
  ['rice cakes', '米饼'],
  ['wafers', '薄脆饼干'],
  ['hard', '硬质'],
  ['made from home recipe or purchased at a bakery', '家庭自制或面包店制作'],
  ['made from home recipe or purchased at bakery', '家庭自制或面包店制作'],
  ['commercially prepared', '市售配方'],
  ['prepared from recipe', '按食谱制作'],
  ['reduced calorie and/or high fiber', '较低热量和/或高纤维'],
  ['reduced-calorie', '较低热量'],
  ['ns as to major flour', '未注明主要面粉种类'],
  ['white or nfs', '白面包或未细分'],
  ['special formula', '特殊配方'],
  ['added fiber', '添加膳食纤维'],
  ['bread stuffing', '面包填料'],
  ['sweet yeast bread', '酵母发酵甜面包'],
  ['challah', '哈拉面包'],
  ['bread crumbs', '面包屑'],
  ['corn muffin mix', '玉米麦芬预拌粉'],
  ['cornbread', '玉米面包'],
  ['whole-wheat', '全麦'],
  ['whole wheat', '全麦'],
  ['whole-grain', '全谷物'],
  ['whole grain', '全谷物'],
  ['multi-grain', '杂粮'],
  ['multigrain', '杂粮'],
  ['cracked wheat', '碎麦'],
  ['cracked-wheat', '碎麦'],
  ['oat bran', '燕麦麸'],
  ['rice bran', '米糠'],
  ['brown rice flour', '糙米粉'],
  ['rice flour', '米粉'],
  ['tapioca starch', '木薯淀粉'],
  ['corn starch', '玉米淀粉'],
  ['rice starch', '米淀粉'],
  ['potato extract', '土豆提取物'],
  ['nonfat dry milk', '脱脂奶粉'],
  ['low fat (2%) milk', '低脂牛奶（脂肪2%）'],
  ['gluten-free', '无麸质'],
  ['gluten free', '无麸质'],
  ['high fiber', '高纤维'],
  ['low sodium', '低钠'],
  ['no salt', '未加盐'],
  ['dry mix', '干预拌粉'],
  ['sour dough', '酸面团'],
  ['sourdough', '酸面团'],
  ['pumpernickel', '粗黑麦面包'],
  ['rye', '黑麦'],
  ['wheat', '小麦'],
  ['barley', '大麦'],
  ['buckwheat', '荞麦'],
  ['millet', '小米'],
  ['quinoa', '藜麦'],
  ['bran', '麸皮'],
  ['soy', '大豆'],
  ['gluten', '面筋'],
  ['flour', '面粉'],
  ['grain', '谷粒'],
  ['cinnamon', '肉桂'],
  ['raisin', '葡萄干'],
  ['raisins', '葡萄干'],
  ['pumpkin', '南瓜'],
  ['zucchini', '西葫芦'],
  ['sunflower meal', '葵花籽粉'],
  ['nut', '坚果'],
  ['nuts', '坚果'],
  ['fruit', '水果'],
  ['vegetable', '蔬菜'],
  ['onion', '洋葱'],
  ['molasses', '糖蜜'],
  ['margarine', '人造黄油'],
  ['tapioca', '木薯'],
  ['toasted', '烤过'],
  ['refrigerated', '冷藏'],
  ['sprouted', '发芽'],
  ['seasoned', '调味'],
  ['grated', '磨碎'],
  ['dry', '干燥'],
  ['puerto rican style', '波多黎各式'],
  ['grecian', '希腊式'],
  ['armenian', '亚美尼亚式'],
  ['mexican', '墨西哥式'],
  ['lard', '猪油'],
  ['water', '水'],
  ['beef jerky', '牛肉干'],
  ['chopped and formed', '切碎重塑'],
  ['top round', '后腿内侧肉'],
  ['bottom round', '后腿外侧肉'],
  ['eye of round', '后腿眼肉'],
  ['top sirloin', '上腰脊肉'],
  ['bottom sirloin', '下腰脊肉'],
  ['short loin', '前腰脊肉'],
  ['strip loin', '外脊肉'],
  ['tenderloin', '里脊'],
  ['rib eye', '肋眼'],
  ['ribeye', '肋眼'],
  ['short ribs', '牛小排'],
  ['chuck eye', '肩胛眼肉'],
  ['brisket', '胸腹肉'],
  ['flank', '腹胁肉'],
  ['skirt steak', '横膈膜牛排'],
  ['shank', '腱子肉'],
  ['sirloin', '腰脊肉'],
  ['chuck', '肩胛肉'],
  ['round', '后腿肉'],
  ['loin', '腰脊肉'],
  ['separable lean and fat', '瘦肉及脂肪'],
  ['separable lean only', '仅瘦肉'],
  ['lean and fat eaten', '瘦肉与脂肪均食用'],
  ['lean only eaten', '仅食用瘦肉'],
  ['lean and fat', '瘦肉及脂肪'],
  ['lean only', '仅瘦肉'],
  ['fat not eaten', '不吃肥肉'],
  ['fat eaten', '食用肥肉'],
  ['skin and breading removed', '去皮及裹粉'],
  ['skin not eaten', '不吃皮'],
  ['skin eaten', '食用皮'],
  ['meat and skin with breading', '肉、皮及裹粉'],
  ['meat and skin and breading', '肉、皮及裹粉'],
  ['meat and skin', '肉及皮'],
  ['meat only', '仅肉'],
  ['skinless', '去皮'],
  ['without skin', '去皮'],
  ['with skin', '带皮'],
  ['boneless', '去骨'],
  ['bone-in', '带骨'],
  ['grass-fed', '草饲'],
  ['all grades', '混合等级'],
  ['select', 'USDA Select级'],
  ['choice', 'USDA Choice级'],
  ['prime', 'USDA Prime级'],
  ['pan-broiled', '平底锅干煎'],
  ['pan-fried', '平底锅煎'],
  ['stir-fried', '炒制'],
  ['deep-fried', '油炸'],
  ['grilled', '炙烤'],
  ['broiled', '上火烤制'],
  ['braised', '炖焖'],
  ['roasted', '烤制'],
  ['baked', '烘烤'],
  ['steamed', '蒸制'],
  ['boiled', '水煮'],
  ['fried', '煎炸'],
  ['stewed', '炖制'],
  ['smoked', '烟熏'],
  ['dried', '干制'],
  ['dehydrated', '脱水'],
  ['canned', '罐装'],
  ['frozen', '冷冻'],
  ['reheated', '复热'],
  ['breaded', '裹粉'],
  ['breading', '裹粉'],
  ['cured', '腌制'],
  ['ground', '绞肉'],
  ['patty', '肉饼'],
  ['patties', '肉饼'],
  ['steak', '肉排'],
  ['roast', '整块肉'],
  ['jerky', '肉干'],
  ['without added fat', '未额外加油'],
  ['with added fat', '额外加油'],
  ['with sauce', '含酱汁'],
  ['without salt', '未加盐'],
  ['with salt', '加盐'],
  ['no salt added', '未加盐'],
  ['not specified', '未说明'],
  ['ns as to', '未说明'],
  ['nfs', '未细分'],
  ['ns', '未说明'],
  ['ready-to-eat', '即食'],
  ['ready-to-serve', '即食'],
  ['prepared', '调制后'],
  ['low fat', '低脂'],
  ['lowfat', '低脂'],
  ['reduced fat', '减脂型'],
  ['nonfat', '脱脂'],
  ['fat free', '无脂'],
  ['fat-free', '无脂'],
  ['whole milk', '全脂牛奶'],
  ['skim milk', '脱脂牛奶'],
  ['unsweetened', '无添加糖'],
  ['sweetened', '加糖'],
  ['plain', '原味'],
  ['extra firm', '特硬质'],
  ['firm', '硬质'],
  ['soft', '软质'],
  ['silken', '嫩滑型'],
  ['sweet potato', '红薯'],
  ['sweet potatoes', '红薯'],
  ['egg white', '蛋清'],
  ['egg yolk', '蛋黄'],
  ['olive oil', '橄榄油'],
  ['soybean oil', '豆油'],
  ['canola oil', '菜籽油'],
  ['breast', '胸肉'],
  ['breasts', '胸肉'],
  ['thigh', '大腿肉'],
  ['thighs', '大腿肉'],
  ['drumstick', '小腿肉'],
  ['drumsticks', '小腿肉'],
  ['wing', '翅'],
  ['wings', '翅'],
  ['rib', '肋部'],
  ['ribs', '肋排'],
  ['liver', '肝'],
  ['kidney', '肾'],
  ['tongue', '舌'],
  ['tripe', '肚'],
  ['heart', '心'],
  ['brain', '脑'],
  ['variety meats and by-products', '内脏及副产品'],
  ['beef', '牛肉'],
  ['pork', '猪肉'],
  ['lamb', '羊肉'],
  ['chicken', '鸡肉'],
  ['duck', '鸭肉'],
  ['turkey', '火鸡肉'],
  ['veal', '小牛肉'],
  ['salmon', '三文鱼'],
  ['tuna', '金枪鱼'],
  ['cod', '鳕鱼'],
  ['shrimp', '虾'],
  ['fish', '鱼'],
  ['tofu', '豆腐'],
  ['yogurt', '酸奶'],
  ['soymilk', '豆浆'],
  ['milk', '牛奶'],
  ['cheese', '奶酪'],
  ['butter', '黄油'],
  ['rice', '米'],
  ['noodles', '面条'],
  ['pasta', '意面'],
  ['bread', '面包'],
  ['oats', '燕麦'],
  ['oatmeal', '燕麦粥'],
  ['corn', '玉米'],
  ['egg', '鸡蛋'],
  ['eggs', '鸡蛋'],
  ['potato', '土豆'],
  ['potatoes', '土豆'],
  ['broccoli', '西兰花'],
  ['spinach', '菠菜'],
  ['lettuce', '生菜'],
  ['cucumber', '黄瓜'],
  ['tomatoes', '番茄'],
  ['tomato', '番茄'],
  ['mushrooms', '蘑菇'],
  ['carrots', '胡萝卜'],
  ['onions', '洋葱'],
  ['cabbage', '甘蓝'],
  ['peanuts', '花生'],
  ['almonds', '杏仁'],
  ['walnuts', '核桃'],
  ['beans', '豆类'],
  ['apples', '苹果'],
  ['apple', '苹果'],
  ['bananas', '香蕉'],
  ['banana', '香蕉'],
  ['oranges', '橙子'],
  ['strawberries', '草莓'],
  ['blueberries', '蓝莓'],
  ['mangoes', '芒果'],
  ['avocados', '牛油果'],
  ['grapes', '葡萄'],
  ['watermelon', '西瓜'],
  ['sandwich', '三明治'],
  ['salad', '沙拉'],
  ['soup', '汤'],
  ['pizza', '披萨'],
  ['stew', '炖菜'],
  ['snacks', '零食'],
  ['fast foods', '快餐'],
  ['restaurant', '餐馆配方'],
  ['oil', '油'],
  ['salt', '盐'],
  ['sugar', '糖'],
  ['coffee', '咖啡'],
  ['tea', '茶'],
  ['brown', '棕色'],
  ['white', '白色品种'],
  ['long-grain', '长粒'],
  ['enriched', '营养强化'],
  ['unenriched', '未营养强化'],
  ['raw', '生'],
  ['cooked', '熟'],
];
const dictionary = [...foodTranslationPhrases]
  .sort((a, b) => b[0].length - a[0].length)
  .map(
    ([en, zh]) =>
      [
        new RegExp(`\\b${en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'gi'),
        zh,
      ] as const,
  );
export function translatedName(description: string) {
  let label = description
    .replace(/^Bread, reduced-calorie, ([^,]+)/i, 'Bread, $1, reduced-calorie')
    .replace(/\bRice, brown\b/gi, '糙米')
    .replace(/\bRice, white\b/gi, '白米')
    .replace(/,\s*round,\s*(?=top round|bottom round|eye of round)/gi, ', ')
    .replace(
      /\bground\b/gi,
      /\b(beef|pork|lamb|chicken|turkey|veal)\b/i.test(description)
        ? '绞肉'
        : '磨碎',
    )
    .replace(
      /(\d+(?:\.\d+)?)% lean meat\s*\/\s*(\d+(?:\.\d+)?)% fat/gi,
      '瘦肉 $1% / 脂肪 $2%',
    )
    .replace(/trimmed to ([\d/]+)" fat/gi, '外层脂肪修至 $1 英寸');
  for (const [pattern, value] of dictionary)
    label = label.replace(pattern, value);
  if (/^bread\b/i.test(description))
    label = label
      .replace(/\bmade with\b/gi, '使用')
      .replace(/\bincludes\b/gi, '包含')
      .replace(/\bwith\b/gi, '含')
      .replace(/\band\/or\b/gi, '和/或')
      .replace(/\band\b/gi, '和')
      .replace(/\bor\b/gi, '或')
      .replace(/\bnative\b/gi, '当地式')
      .replaceAll('白色品种', '白面包型');
  return label
    .replace(/\s*,\s*/g, ' · ')
    .replace(/\s+/g, ' ')
    .trim();
}
export function displayFoodName(food: Food) {
  return food.originalName && food.source?.startsWith('USDA FDC ')
    ? food.localizedName || translatedName(food.originalName)
    : food.name;
}
